config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#title'
  resources :books

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :set_book, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show, :title]
  def title
  end
  
  
  def create
    
    @book = Book.new
    @book.title = params[:book][:title]
    @book.writer = params[:book][:writer]
    @book.content = params[:book][:content]
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def update
    @book.title = params[:book][:title]
    @book.writer = params[:book][:writer]
    @book.content = params[:book][:content]
    @book.save
    redirect_to book_path
  end

  def destroy
  @book.destroy
  redirect_to books_path
  end
  
  private
  
  def set_book
    @book = Book.find(params[:id])
    @books = Book.all
  end
  
  def book_params
    params.require(:book).permit(:title, :writer, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
   <%= form_for(@book) do |f| %>
          <h5 class="card-title"><p>제목</p><%= f.text_field :title %></h5>
          <p class="card-text"><p>작가</p><%= f.text_field :writer %><br></p>
          <p class="card-text"><p>내용</p><%= f.text_area :content %><br></p>
          <p class="card-text"><%= f.submit '저장' %><br></p>
   <% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destory.html.erb
<h1>Books#destory</h1>
<p>Find me in app/views/books/destory.html.erb</p>

app/views/books/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    
     <div class="d-flex justify-content-around">
       <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <%= form_for(@book, url: book_path, method: 'patch') do |f| %>
        <div class="card-header">내용수정</div>
          <div class="card-body">
            <%= render 'form' %> 
            <!--<h5 class="card-title"><p>제목</p><%= f.text_field :title %></h5>-->
            <!--<p class="card-text"><p>작가</p><%= f.text_field :writer %><br></p>-->
            <!--<p class="card-text"><p>내용</p><%= f.text_area :content %><br></p>-->
            <!--<p class="card-text"><%= f.submit '수정완료' %><br></p>-->
          </div>
        <% end %>
      </div>
    </div>
    
    
    
    
      <!--<h1>내용수정</h1>-->
      <!--<%= form_for(@book, url: book_path, method: 'patch') do |f| %>-->
      <!--    <h1><%= @book.id %> : <%= f.text_field :title %></h1> -->
      <!--    <h2>작가 <%= f.text_field :writer %></h2> -->
      <!--    <h2>내용 <%= f.text_area :content %></h2>-->
      <!--    <%= f.submit '수정완료' %>-->
      <!--<% end %>-->
 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/books/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>


  
  
  <h3 align ="center">추천 도서</h3>
  
  <div class = "container">
     <div class="row">
        <% @books.each do |b| %>
         <div class="col-md-3">
           <div class = "card">
            <div class="card-body">
               <h5> <%= link_to b.title, book_path(id: b.id) %> </h5>
              <p class="card-title"><strong>저자</strong> : <%= b.writer   %></p>
              <p class="card-text"><strong>줄거리</strong> <br><%= b.content %></p>
            </div>           
          </div>  
         </div>
        <% end %>     
     </div>
  </div>  
    <div class="d-flex justify-content-center">
    <%= link_to '[새로작성하기]', new_book_path %>
    </div>
  
  <!-- <div class="d-flex align-content-stretch flex-wrap">-->
      
  <!--      <% @books.each do |b| %>-->
  <!--        <div class="card bg-light mb-3" style="max-width: 18rem;">-->
  <!--          <div class="card-header"><a href = '/books/<%= b.id %>'><%= b.title %></a></div>-->
  <!--            <div class="card-body">-->
  <!--              <p class="card-title"><strong>저자</strong> : <%= b.writer   %></p>-->
  <!--              <p class="card-text"><strong>줄거리</strong> <br><%= b.content %></p>-->
  <!--            </div>-->
  <!--          </div>-->
  <!--      <% end %>     -->
  <!--        </div>-->
       <!--<div class="d-flex justify-content-center">-->
         
       <!--  <a class="btn btn-primary" href='/books/new' role="button" align = "center" >새로작성하기</a>-->
  <!--     </div>-->
  <!--</div>-->
   
   
   
   

    
    
    
    
    
    

   
            
   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>

app/views/books/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   
    
    <div class="d-flex justify-content-around">
      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <%= form_for(@book, url: books_path, method: 'post') do |f| %>
        <div class="card-header">감명깊게 읽은 책을 입력해 주세요</div>
        <div class="card-body">
          <%= render 'form' %>
          <!--<h5 class="card-title"><p>제목</p><%= f.text_field :title %></h5>-->
          <!--<p class="card-text"><p>작가</p><%= f.text_field :writer %><br></p>-->
          <!--<p class="card-text"><p>내용</p><%= f.text_area :content %><br></p>-->
          <!--<p class="card-text"><%= f.submit '저장' %><br></p>-->
        </div>
        <% end %>
      </div>
    </div>
    
    <!--<h1>감명깊게 읽은 책을 입력해 주세요</h1>-->
    <!--<%= form_for(@book, url: books_path, method: 'post') do |f| %>-->
    <!--    <p>제목</p><%= f.text_field :title %><br>-->
    <!--    <p>작가</p><%= f.text_field :writer %><br>-->
    <!--    <p>내용</p><%= f.text_area :content %><br>-->
    <!--    <%= f.submit '저장' %>-->
    <!--<% end %>-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/books/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="mx-auto" style="width: 1000px;">
      
        <div class="card bg-dark text-white">
          <img class="card-img" src="https://goodereader.com/blog/uploads/images/personal-finance-books.jpg" alt="Card image">
          <div class="card-img-overlay">
            <h5 class="card-title"><%= @book.title %></h5>
            <p class="card-text"><strong>줄거리</strong> <br><%= @book.content %></p>
            <p class="card-text">wirte by <br> <%= @book.writer %></p> 
            
            <% if current_user == @book.user %>
                  <%= link_to '[수정하기]', edit_book_path(book_id: @book.id) %>
                  <%= link_to '[삭제하기]', book_path, method: :delete %>
              </tr>
            <% end %>
            <br>
            <%= link_to '[목록으로]', books_path %>
            <p>이글은 <%= @book.user.email %>님이 작성하셨습니다</p>
            <!--<a class="btn btn-primary" href='/books' role="button">목록으로</a>-->
          </div>
        </div>
      
        <!--<h2><%= @book.id %> : <%= @book.title %></h2>-->
        <!--<br>-->
        <!--<h3>작가</h3> <%= @book.writer %>-->
        <!--<h3>내용</h3> <%= @book.content %>-->
        
        <!--<br><br><br><br>-->
        
        
        
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/books/title.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   
    <div class="card bg-dark text-white">
      <img class="card-img" src="https://www.brisbane.qld.gov.au/sites/default/files/trumba/events/dgdzhbdbnghqvvogxw8biu7o_6.jpg" alt="Card image">
      <div class="card-img-overlay">
        <blockquote class="blockquote text-center">
          <% if user_signed_in? %>
            <p style="font-size: 200px">&nbsp</p>
            <p class="mb-0" style="font-size: 70px"><span style="color:black"><%= link_to '오늘 뭐 읽지?',books_path %></span></p>
            <footer class="blockquote-footer">우리들의 추천도서 <cite title="Source Title">in likelionkonkuk</cite></footer>
            <%= link_to '[로그아웃]',destroy_user_session_path,method: :delete %> <%= link_to '[회원가입]',new_user_registration_path %>
          <% else %>
            <p style="font-size: 200px">&nbsp</p>
            <p class="mb-0" style="font-size: 70px"><span style="color:black">오늘 뭐 읽지?</span></p>
            <footer class="blockquote-footer">로그인을 해주세요 <cite title="Source Title"></cite></footer>
            <%= link_to '[로그인]',new_user_session_path %> <%= link_to '[회원가입]',new_user_registration_path %>
          <% end %>  
        </blockquote>
      </div>
    </div>
    
    
    
   
    
    

   
    
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>오늘 뭐읽지?</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  </head>

<body>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
    <% if user_signed_in? %>
      <ul>
        <li><%= current_user.email %> 님 환영합니다</li>
        <li><%= link_to '[로그아웃]', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to '[회원정보 수정]', edit_user_registration_path %></li>

      </ul>
      <% else %>
      <ul>
        <li><%= link_to '[회원가입]', new_user_registration_path %></li>
        <li><%= link_to '[로그인]', new_user_session_path %></li>      
      </ul>
    <% end %>       

<%= yield %>

</body>
</html>